# k: keyboard keys (0-9, A-Z, F1-F24, Enter, Space, Shift, Ctrl, Alt, arrows, etc.)
# m: mouse actions (x, x+, x-, y, y+, y-, lb, rb, mb, mw, mw+, mw-, x1, x2)
# x: xinput actions (a, b, x, y, lb, rb, back, start, ls, rs, guide, up, down, left, right, lt, rt, lx, lx+, lx-, ly, ly+, ly-, rx, rx+, rx-, ry, ry+, ry-)
# o: internal actions (alt_mode, gyro_stop_all, gyro_stop_x, gyro_stop_y, gyro_stop_z, accel_reset_all, accel_reset_x, accel_reset_y, accel_reset_z)

[Misc]
Path=
Name=Default (Hybrid mode)
Comments=XInput with Mouse Aiming. PS Move 1: Aiming(Hold Move button to reposition). PS Move 2: Movement(Move button to reset position). PS Navigation: Movement.

[Move1]
CROSS=x:a
CIRCLE=x:b
SQUARE=x:x
TRIANGLE=x:y
SELECT=x:up
START=x:down
PS=x:back
MOVE=o:alt_mode
TRIGGER=x:rt
GYRO_X=m:y
GYRO_X+=
GYRO_X-=
GYRO_Y=
GYRO_Y+=
GYRO_Y-=
GYRO_Z=m:x
GYRO_Z+=
GYRO_Z-=
ACCEL_X=
ACCEL_X+=
ACCEL_X-=
ACCEL_Y=
ACCEL_Y+=
ACCEL_Y-=
ACCEL_Z=
ACCEL_Z+=
ACCEL_Z-=

[MoveTrigger1]
Invert=0
Sensitivity=1.0
Deadzone=0

[MoveGyroscope1]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=0.1
SensitivityY=0.04
SensitivityZ=0.1
DeadzoneX=5
DeadzoneY=8
DeadzoneZ=8

[MoveAccelerometer1]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=1.0
SensitivityY=1.0
SensitivityZ=2.0
DeadzoneX=400
DeadzoneY=400
DeadzoneZ=400

[AltMove1]
CROSS=
CIRCLE=
SQUARE=
TRIANGLE=
SELECT=
START=
PS=
MOVE=
TRIGGER=
GYRO_X=
GYRO_X+=
GYRO_X-=
GYRO_Y=
GYRO_Y+=
GYRO_Y-=
GYRO_Z=
GYRO_Z+=
GYRO_Z-=
ACCEL_X=
ACCEL_X+=
ACCEL_X-=
ACCEL_Y=
ACCEL_Y+=
ACCEL_Y-=
ACCEL_Z=
ACCEL_Z+=
ACCEL_Z-=

[AltMoveTrigger1]
Invert=0
Sensitivity=1.0
Deadzone=0

[AltMoveGyroscope1]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=0.7
SensitivityY=0.7
SensitivityZ=0.7
DeadzoneX=4000
DeadzoneY=2000
DeadzoneZ=4000

[AltMoveAccelerometer1]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=1.0
SensitivityY=1.0
SensitivityZ=1.0
DeadzoneX=300
DeadzoneY=300
DeadzoneZ=500

[Move2]
CROSS=x:rs
CIRCLE=x:ls
SQUARE=x:lb
TRIANGLE=x:rb
SELECT=x:right
START=x:left
PS=x:start
MOVE=o:accel_reset_all
TRIGGER=x:lt
GYRO_X=
GYRO_X+=
GYRO_X-=
GYRO_Y=
GYRO_Y+=
GYRO_Y-=
GYRO_Z=
GYRO_Z+=
GYRO_Z-=
ACCEL_X=x:lx
ACCEL_X+=
ACCEL_X-=
ACCEL_Y=
ACCEL_Y+=
ACCEL_Y-=
ACCEL_Z=x:ly
ACCEL_Z+=
ACCEL_Z-=

[MoveTrigger2]
Invert=0
Sensitivity=1.0
Deadzone=0

[MoveGyroscope2]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=0.05
SensitivityY=0.05
SensitivityZ=0.05
DeadzoneX=20
DeadzoneY=20
DeadzoneZ=600

[MoveAccelerometer2]
InvertX=1
InvertY=0
InvertZ=0
SensitivityX=1.0
SensitivityY=1.0
SensitivityZ=2.0
DeadzoneX=400
DeadzoneY=400
DeadzoneZ=1500

[AltMove2]
CROSS=
CIRCLE=
SQUARE=
TRIANGLE=
SELECT=
START=
PS=
MOVE=
TRIGGER=
GYRO_X=
GYRO_X+=
GYRO_X-=
GYRO_Y=
GYRO_Y+=
GYRO_Y-=
GYRO_Z=
GYRO_Z+=
GYRO_Z-=
ACCEL_X=
ACCEL_X+=
ACCEL_X-=
ACCEL_Y=
ACCEL_Y+=
ACCEL_Y-=
ACCEL_Z=
ACCEL_Z+=
ACCEL_Z-=

[AltMoveTrigger2]
Invert=0
Sensitivity=1.0
Deadzone=0

[AltMoveGyroscope2]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=1.0
SensitivityY=1.0
SensitivityZ=1.0
DeadzoneX=80
DeadzoneY=80
DeadzoneZ=150

[AltMoveAccelerometer2]
InvertX=1
InvertY=0
InvertZ=1
SensitivityX=1.0
SensitivityY=1.0
SensitivityZ=1.0
DeadzoneX=300
DeadzoneY=300
DeadzoneZ=500

[Rumble]
Enabled=1
MasterStrength=0.8
CombineWhenSingleMove=1
LargeMinActive=10
LargeLowThreshold=45
LargeMidThreshold=120
LargeBoostLow=3.2
LargeBoostMid=1.9
LargeBoostHigh=1.15
LargeMinOutput=90
SmallMinActive=5
SmallLowThreshold=20
SmallMidThreshold=90
SmallBoostLow=4.0
SmallBoostMid=2.2
SmallBoostHigh=1.2
SmallMinOutput=70

[Navigator1]
CROSS=x:rs
CIRCLE=x:rb
L1=x:lb
L2=x:lt
L3=x:ls
PS=x:start
UP=x:up
RIGHT=x:right
DOWN=x:down
LEFT=x:left
X=x:lx
X+=
X-=
Y=x:ly
Y+=
Y-=

[NavigatorTrigger1]
Invert=0
Sensitivity=1.0
Deadzone=0

[NavigatorStick1]
InvertX=0
InvertY=1
SensitivityX=1.0
SensitivityY=1.0
DeadzoneX=12
DeadzoneY=12

[AltNavigator1]
CROSS=
CIRCLE=
L1=
L2=
L3=
PS=
UP=
RIGHT=
DOWN=
LEFT=
X=
X+=
X-=
Y=
Y+=
Y-=

[AltNavigatorTrigger1]
Invert=0
Sensitivity=1.0
Deadzone=0

[AltNavigatorStick1]
InvertX=0
InvertY=1
SensitivityX=1.0
SensitivityY=1.0
DeadzoneX=12
DeadzoneY=12

[Navigator2]
CROSS=
CIRCLE=
L1=
L2=
L3=
PS=
UP=
RIGHT=
DOWN=
LEFT=
X=
X+=
X-=
Y=
Y+=
Y-=

[NavigatorTrigger2]
Invert=0
Sensitivity=1.0
Deadzone=0

[NavigatorStick2]
InvertX=0
InvertY=1
SensitivityX=1.0
SensitivityY=1.0
DeadzoneX=12
DeadzoneY=12

[AltNavigator2]
CROSS=
CIRCLE=
L1=
L2=
L3=
PS=
UP=
RIGHT=
DOWN=
LEFT=
X=
X+=
X-=
Y=
Y+=
Y-=

[AltNavigatorTrigger2]
Invert=0
Sensitivity=1.0
Deadzone=0

[AltNavigatorStick2]
InvertX=0
InvertY=1
SensitivityX=1.0
SensitivityY=1.0
DeadzoneX=12
DeadzoneY=12

[RepeatMs]
Key=120
Wheel=50
